### ISSUE TITLE
Issues with CLI usage

### ISSUE THREAD

**Issue by thorstenkampe** [pahaz/sshtunnel#100]
Let's compare a `ssh` and the equivalent `sshtunnel` command:
```
ssh -p 2222                             \
    -L localhost:40000:remote_host:3306 \
    user@proxy_host
```
```
sshtunnel -p 2222                      \
          -L localhost:40000           \
          -R remote_host:3306          \
          -U user                      \
          proxy_host
```

1. `sshtunnel` uses `-L` for local port forwarding (like `ssh`) and `-R` for the second part of the local port forwarding. `ssh` uses `-R` for remote port forwarding - which is something completely different.

2. `sshtunnel` has `-x proxy_host:proxy_port` . When `-x` is used, `-p SSH_PORT` and `ssh_address` are silently ignored.

**Comment by fernandezcuesta** [comment]
Could have been named other way (`-S` or `-Q`) but `-R` was chosen. I agree at first it might lead to confusion, but it is documented.
