### ISSUE TITLE
Dynamic port binding doesn't work.

### ISSUE THREAD

**Issue by 1dziubo1** [pahaz/sshtunnel#104]
with SSHTunnelForwarder(
                    (ip, port)),
                    ssh_username=ssh_username,
                    ssh_password=ssh_password,
                    remote_bind_address=(remote_ip, remote_port),
                    local_bind_address=(host_ip, host_port),
            ):
               # -- code --

If host_port has defined value, e.g. host_ip=10020
Code works and connection is set. However I want to bind to first free port. According to documentation, I should just remove this parameter:

    with SSHTunnelForwarder(
                    (ip, port)),
                    ssh_username=ssh_username,
                    ssh_password=ssh_password,
                    remote_bind_address=(remote_ip, remote_port),
                    local_bind_address=(host_ip, ),
            ):

Unfortunately that results in error:

    File "C:\Python27\lib\socket.py", line 575, in create_connection
        raise err
    socket.error: [Errno 10061] No connection could be made because the target machine actively refused it

What can be a reason to that behavior?

**Comment by bsamuel-ui** [comment]
Is `host_ip` the IP address of a local network device, i.e. 127.0.0.1?

In particular, can you run: ```
from socket import socket
s = socket()
s.bind((host_ip, 0))
print(s.getsockname())
```
If not, paramiko is probably going to have issues to, especially if you're trying to get a random port from a remote device :-)

**Comment by 1dziubo1** [comment]
I've found a bug in configuration at my side, sorry for inconvinience.
