### ISSUE TITLE
How do I use key to connect?

### ISSUE THREAD

**Issue by lizhaode** [pahaz/sshtunnel#105]
I write these:

```python
    with open('/Users/lizhao/Downloads/adb.pem') as f:
        key = f.read()
    server = SSHTunnelForwarder(ssh_address_or_host='111.111.111.111',ssh_username='centos',remote_bind_address=('127.0.0.1',13599),ssh_host_key=key)
    server.start()
    print server.local_bind_address
    server.stop()
```

It throws these:

Traceback (most recent call last):
  File "/Users/lizhao/Documents/AutoTest/guardianRuleTest/lib/MySqlQuery.py", line 32, in <module>
    server = SSHTunnelForwarder(ssh_address_or_host='111.111.111.111',ssh_username='centos',remote_bind_address=('127.0.0.1',13599),ssh_host_key=key)
  File "/usr/local/lib/python2.7/site-packages/sshtunnel.py", line 892, in __init__
    logger=self.logger
  File "/usr/local/lib/python2.7/site-packages/sshtunnel.py", line 1031, in _consolidate_auth
    raise ValueError('No password or public key available!')
ValueError: No password or public key available!

**Comment by bsamuel-ui** [comment]
This is explained in the manual... though it assumes you're fairly familiar with ssh. From `help(SSHTunnelForwarder)`:
```
        ssh_host_key (str):
            Representation of a line in an OpenSSH-style "known hosts"
            file.

            ``REMOTE GATEWAY``'s key fingerprint will be compared to this
            host key in order to prevent against SSH server spoofing.
            Important when using passwords in order not to accidentally
            do a login attempt to a wrong (perhaps an attacker's) machine
```

You want the `ssh_pkey` parameter, which corresponds to the `-i` parameter of `ssh` and takes a path to the private key.

**Comment by lizhaode** [comment]
Thx!
But I have a new question.

In my command , is `ssh -i a.pem -i b.pem  root@192.168.3.4` 
Can I take tow keys?

**Comment by bsamuel-ui** [comment]
Not through that option.

If you're writing a utility that needs to let users provide multiple keys, I'd recommend pushing the complexity of managing that to `ssh-agent` as it has a robust interface. If a user enters these commands:
```
eval `ssh-agent`
ssh-add key1.pem
ssh-add key2.pem
python your-ssh-tunnel-script.py
ssh-agent -k
```
What happens is the `ssh-agent` command forks off a daemon and outputs some bash to set and export environment variables it needs. Then `ssh-add` loads each file into the agent. Your script gets the agent configuration in its environment and sees those keys, finally `-k` kills the agent.
