### ISSUE TITLE
Question: way to catch server unavailable on remote

### ISSUE THREAD

**Issue by tangb** [pahaz/sshtunnel#107]
Hi

I have this code:
```
self.tunnel = SSHTunnelForwarder(
    (self.remote_host, self.remote_port),
    ssh_username=self.ssh_username,
    ssh_password=self.ssh_password,
    remote_bind_address=(u'127.0.0.1', self.forward_port)
 )
 self.tunnel.start()

self.socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
self.socket.connect((u'127.0.0.1', self.tunnel.local_bind_port))
```

Tunnel is connected successfully and socket connection succeed too while the remote the server is not launched (listening on self.forward_port) and i got these messages:
```
2017-11-24 23:45:34,943| ERROR   | Secsh channel 0 open FAILED: Connection refused: Connect failed
2017-11-24 23:45:34,943 ERROR : Secsh channel 0 open FAILED: Connection refused: Connect failed
2017-11-24 23:45:34,946| ERROR   | Could not establish connection from ('127.0.0.1', 36139) to remote side of the tunnel
2017-11-24 23:45:34,946 ERROR : Could not establish connection from ('127.0.0.1', 36139) to remote side of the tunnel
```

My question is how can i catch these errors on caller side and relaunch socket connection as long as server is not listening.

Thank you for your answer ;-)

**Comment by bsamuel-ui** [comment]
I believe setting `self.tunnel.skip_tunnel_checkup = False` before you start your tunnel will run a check that should fail fast and allow you to retry.

But I've found it's very robust to attempt a connection over the tunnel than to try and check for specific errors. I'd call `self.socket.settimeout()` before you connect your socket to force quick failure, and that has the advantage that it only succeeds when everything is in place.

Also make sure you're closing those failed connections!

**Comment by fernandezcuesta** [comment]
Yeap, the `skip_tunnel_checkup` was set to True by default; that parameter was meant just for that (doing a fast check that the remote side is up/down) but the suggestion made by @bsamuel-ui should also work.
