### ISSUE TITLE
AttributeError: 'ProxyCommand' object has no attribute '_closed'

### ISSUE THREAD

**Issue by sohaibfarooqi** [pahaz/sshtunnel#108]
Hi,
I have tried an example from docs. The SSHTunnel is established successfully, but as some point the code throws the error:
`AttributeError: 'ProxyCommand' object has no attribute '_closed'`

     with SSHTunnelForwarder(ip,
		    remote_bind_address=(ip, 9200),
		    ssh_config_file=Config.SSH_FILE_PATH,
		    local_bind_address=(Config.ES_HOST, port),
		    set_keepalive=360) as tunnel:
                    tunnel.start()
                    #This prints correct output
                    print(requests.get("http://ip:port").content) 
                    tunnel.stop() #This line throws error

I have tried removing `start` and `stop` functions and have tried changing above code to [this](https://sshtunnel.readthedocs.io/en/latest/#example-2) example from docs. Still giving the same error. 
Is there a way to solve this error? 

Thanks,
Sohaib

**Comment by fernandezcuesta** [comment]
Did you installed from source or PyPI?

**Comment by sohaibfarooqi** [comment]
PyPI

**Comment by sohaibfarooqi** [comment]
The issue is, If an exception occurs between `start` and `stop` this error is thrown. SSH connection won't get closed in case of exception?

**Comment by fernandezcuesta** [comment]
My fault, didn't update pypi for a while. Will do it shortly, meanwhile please install from source.
