### ISSUE TITLE
Error reading SSH protocol banner

### ISSUE THREAD

**Issue by sohaibfarooqi** [pahaz/sshtunnel#109]
Hi,
I am using sshtunnel build from source. I keep getting this error:
**code**:
    
       with SSHTunnelForwarder(ip,
			    remote_bind_address=(ip, 9200),
			    ssh_config_file=Config.SSH_FILE_PATH,
			    local_bind_address=(Config.ES_HOST, port),
			    set_keepalive=360) as tunnel:

**Error Trace**:
       
    0 keys loaded from agent
    Private key file (/root/.ssh/id_rsa, <class 'paramiko.rsakey.RSAKey'>) successfully loaded
    Connecting to gateway: xx.x.x.xx:22 as user 'user'
    Concurrent connections allowed: True
    Trying to log in with key: b'key'
    Connecting via proxy: 'bastion'
    Exception: Error reading SSH protocol banner

    ERROR | Traceback (most recent call last):
    lib/python3.5/site-packages/paramiko/transport.py", line 1884, in _check_banner
    buf = self.packetizer.readline(timeout)
    lib/python3.5/site-packages/paramiko/packet.py", line 331, in readline
    buf += self._read_timeout(timeout)
    lib/python3.5/site-packages/paramiko/packet.py", line 501, in _read_timeout
    raise socket.timeout()
  
I am able to manually open an ssh tunnel through command line, I use command in this format:
`ssh -i ~/.ssh/id_rsa -L portD:xx.x.x.xx:portH user@bastion`.

Can you please guide me how can I further debug this error?

**Comment by fernandezcuesta** [comment]
What about logging in to bastion with paramiko? What kind of system is it
btw?

**Comment by sohaibfarooqi** [comment]
`bastion` is a ubuntu server on aws. I can log into bastion via paramiko. Moreover I can do ssh into bastion and xx.x.x.xx server via command line using the same configuration file that I am using in code.

**Comment by pahaz** [comment]
It looks like a `paramiko` problem.

**Comment by Red-M** [comment]
@sohaibfarooqi Sorry to necro this issue but could you test something for me by trying out this library?
https://redexpect.readthedocs.io/en/latest/redexpect.html

I've had that same issue in the past with paramiko and I had since moved away to pxssh (which can be found in pexepct) to over come it. If you still can do you mind trying this out for me?

**Comment by pahaz** [comment]
Sorry. It's been so long. If you have some problems, feel free to open a new issue.
