### ISSUE TITLE
_check_tunnel fails when using adresses other than 127.0.0.1

### ISSUE THREAD

**Issue by vcariven** [pahaz/sshtunnel#110]
Hello, 

First of all thank you for this great library !!

In `_check_tunnel(self, _srv)`, to avoid Windows error when trying to connect to `0.0.0.0`, use of `127.0.0.1` is forced:

```python
# Windows raises WinError 10049 if trying to connect to `0.0.0.0`
s.connect(('127.0.0.1', _srv.local_port))
```
When setting up tunnels on addresses picked from `127.0.0.1/8` (loopback ip addres range) (e.g. `127.1.1.1`), `_check_tunnel(self, _srv)` still uses `127.0.0.1` instead of `127.1.1.1` which gives wrong result (a `DOWN` status instead of an `UP`)

Following code would allow to correctly check those tunnels:

```python
# Windows raises WinError 10049 if trying to connect to 0.0.0.0
addr = '127.0.0.1' if _srv.local_address == '0.0.0.0' else _srv.local_host
s.connect((addr, _srv.local_port))
```

Regards

**Comment by fernandezcuesta** [comment]
Hi, thanks for reporting the issue! Solution was almost the same as yours.
