### ISSUE TITLE
What happens if application ends and tunnel is not closed?

### ISSUE THREAD

**Issue by jhfatehi** [pahaz/sshtunnel#118]
Thank you all for creating this.  I am new to SSH and this that been very helpful.  My question is, what happens if my python application is ended while the SSH tunnel is still open?  Is the SSH session still active or does it end when the python application is ended?  Thanks.

**Comment by fernandezcuesta** [comment]
If your applicatio is the one opening the tunnel, then the tunnel will die. You may expect the local ports being blocked for some time though.
