### ISSUE TITLE
Python process hangs indefinitely when error is raised

### ISSUE THREAD

**Issue by josiahjohnston** [pahaz/sshtunnel#127]
If I start an SSH tunnel and some code crashes before `server.stop()` is called, then my python process hangs indefinitely. I'm get this behavior on Ubuntu 16.04 running Python 2.7.12 as well as OS X 10.12.6 running Python 2.7.15, both running sshtunnel v 0.1.2 from `pip install sshtunnel`. I also tested v0.1.4 that I cloned today from this repository into a fresh virtual environment on OS X. It hangs in all cases.

Minimal example:
```
from sshtunnel import SSHTunnelForwarder
server = SSHTunnelForwarder(
    'hostname.com',
    ssh_username="user",
    ssh_pkey="/path/to/id_rsa",
    remote_bind_address=('127.0.0.1', 5432)
)
server.start()
print(server.local_bind_port)  # show assigned local port
raise ValueError('random error')

server.stop()
```

When I run the example, I get:
```
$ python sshtunnel_then_error.py 
45528
Traceback (most recent call last):
  File "foo.py", line 12, in <module>
    raise ValueError('random error')
ValueError: random error
```
At which point the program hangs indefinitely. 

I tried working around with atexit, but to no avail. Snippets from that experiment:
```
import atexit
def _cleanup():
    global server
    try:
        server.stop()
    except:
        pass
atexit.register(_cleanup)
```
Any ideas for fixes or work-arounds? 
Thanks!

**Comment by fernandezcuesta** [comment]
Hi, use `with` context manager instead, for example:

    with sshtunnel.open_tunnel(.... ) as tunnel:
        raise ValueError('random error')



2018-07-06 0:16 GMT+02:00 Josiah Johnston <notifications@github.com>:

**Comment by fernandezcuesta** [comment]
Hi, use `with` context manager instead, for example:

```python
with sshtunnel.open_tunnel(.... ) as tunnel:
    raise ValueError('random error')
```

**Comment by josiahjohnston** [comment]
It would be difficult to rearrange all of my code that depends on the SSH tunnel to be inside a `with` block. 

My current pattern is to write code with a DB connection as a relatively persistent resource that may need to get refreshed periodically. I was hoping to use SSH tunnels the same way to support remote and secure DB connections.

**Comment by fernandezcuesta** [comment]
Closing this issue since it has nothing to do with sshtunnel.
