### ISSUE TITLE
py3 context won't exit

### ISSUE THREAD

**Issue by medecau** [pahaz/sshtunnel#128]
This happens while using ```sshtunnel``` in ```python3``` with the ```with``` context.

```sshtunnel``` does not exit the context.

I was able to work around it by directly calling the ```tunnel._transport.close()```  just before leaving the context.

**Comment by fernandezcuesta** [comment]
what about the logs? You shouldn't need the workaround since `__exit__()` calls `_stop_transport()` which in turn does the transport close.

**Comment by medecau** [comment]
thank you for the quick reply @fernandezcuesta 

I have decided to maintain an SSH tunnel using SSH cli directly and won't be able to follow up on this issue.

**Comment by page1** [comment]
tunnel._transport.close() got this working for me.
I'm installing directly from git.
