### ISSUE TITLE
0.1.2 releases contain different sources

### ISSUE THREAD

**Issue by robi-wan** [pahaz/sshtunnel#129]
I noticed that the [released packages on PYPI](https://pypi.org/project/sshtunnel/0.1.2/#files) contain different sources - the [source package](https://files.pythonhosted.org/packages/dc/06/1d9969bbe7ad6895983016666699af2ab0b24d270c0abdecf51797d126cc/sshtunnel-0.1.2.tar.gz) seems to contain the source for version 0.1.2 but the [wheel package](https://files.pythonhosted.org/packages/e1/b0/e7f0e1cc62a69a93eea7c2f20913c1e3e8f8abd795fe9155995fdc5a02a0/sshtunnel-0.1.2-py2.py3-none-any.whl) contains a newer source (with some commits from 2nd. February 2018).

This is a local diff between `sshtunnel.py` in these two packages:
````diff
--- D:/home/download/lang/python/libs/ssh_tunnel/0.1.2/sshtunnel-0.1.2_src/sshtunnel-0.1.2/sshtunnel.py	Do Okt 27 17:01:54 2016
+++ D:/home/download/lang/python/libs/ssh_tunnel/0.1.2/sshtunnel-0.1.2_whl/sshtunnel.py	Fr Feb  2 10:04:54 2018
@@ -744 +744 @@ class SSHTunnelForwarder(object):
-        return self.tunnel_is_up(target)
+        return self.tunnel_is_up.get(target, True)
@@ -780,0 +781 @@ class SSHTunnelForwarder(object):
+                ssh_forward_server.daemon_threads = self.daemon_forward_servers
@@ -1018 +1019,2 @@ class SSHTunnelForwarder(object):
-            if os.path.exists(ssh_pkey):
+            ssh_pkey_expanded = os.path.expanduser(ssh_pkey)
+            if os.path.exists(ssh_pkey_expanded):
@@ -1020 +1022 @@ class SSHTunnelForwarder(object):
-                    pkey_file=ssh_pkey,
+                    pkey_file=ssh_pkey_expanded,
@@ -1082 +1084 @@ class SSHTunnelForwarder(object):
-                msg = 'Problem setting SSH Forwarder up: {0}'.format(e.args[0])
+                msg = 'Problem setting SSH Forwarder up: {0}'.format(e.value)
@@ -1187 +1189,3 @@ class SSHTunnelForwarder(object):
-            s.connect(('127.0.0.1', _srv.local_port))
+            connect_to = ('127.0.0.1', _srv.local_port) \
+                if _srv.local_host == '0.0.0.0' else _srv.local_address
+            s.connect(connect_to)

**Comment by pahaz** [comment]
Thanks for the report. We are currently changed our release cycle to deploy by CI. I think it will remove the problem for the future. Feel free to reopen an issue if you still have a problem.
