### ISSUE TITLE
missing git tags to corresponding pypi releases

### ISSUE THREAD

**Issue by anthraxx** [pahaz/sshtunnel#139]
Releases published on pypi should also have their corresponding commits tagged in git and published to github for transparency.

Please push missing tags (especially latest)

**Comment by anthraxx** [comment]
why is this a won't fix? Having tags in git is just aiding transparency and for distro released packages im pulling direct sources from github, which is not easily possible without tags.
Is there a specific reason you dong want to tag?

**Comment by anthraxx** [comment]
@fernandezcuesta can you please please take a look? This is really inconvenient and currently holding back the distro released packages in Arch Linux.

Please push some git tags for releases like 0.1.5, i would owe you a beer :beer:

**Comment by fernandezcuesta** [comment]
should be ready now, please let me know otherwise

**Comment by anthraxx** [comment]
Wow, thanks, this is awesome and very very much appreciated. I will release the distro package in the following days.
