### ISSUE TITLE
File Transfer fails and socket closes

### ISSUE THREAD

**Issue by pranky89** [pahaz/sshtunnel#140]
Hi,

I can notice that machines which have fast access to network are dropping the local established port while transferring the packets causing the file transfer to fail whereas slow machines are working fine.
I can see that the paramiko is already using sendall() but still this issue? what could be happening here?
I really like sshtunnel but this issue is making me switch.

**Comment by pahaz** [comment]
Could you please show your code for that case?

**Comment by pahaz** [comment]
Not active for more than a month ... Feel free to reopen if you still have any problem
