### ISSUE TITLE
Multihop ssh with python

### ISSUE THREAD

**Issue by kashabi** [pahaz/sshtunnel#144]
Is it possible to multihop ssh through the 2 routers with python(paramiko or proxy)?

**Comment by pahaz** [comment]
Yes, you can use it for that. 

Example:
 1. host1 has access to host2
 2. host2 has access to service1

It should look like follow:

```
servic1_host = 'servic1'
servic1_port = 3306

with open_tunnel(
    ('host1', 22),
    ssh_username="vagrant",
    ssh_password="vagrant",
    remote_bind_address=('host2', 22)
) as server1:

    print('remote ssh:', server1.local_bind_port)
    with open_tunnel(
        ('localhost', local_bind_port),
        ssh_username="vagrant",
        ssh_password="vagrant",
        remote_bind_address=(servic1_host, servic1_port)
    ) as server2:

        print('remote service:', server2.local_bind_port)
        while True:
            # press Ctrl-C for stopping
            sleep(1)

```

**Comment by pahaz** [comment]
Or you can also use this recipe: https://github.com/pahaz/sshtunnel/issues/92
Feel free to reopen if you still have a problem.

**Comment by MartyMcFlyInTheSky** [comment]
I have host key checking enabled using my known_hosts fingerprints, how to make this work with a bastion host? I figure I would somehow need a way to read the bastion's known_hosts file to jump to the target host or how to do this?
