### ISSUE TITLE
Keeping the tunnel open in the background

### ISSUE THREAD

**Issue by pawelad** [pahaz/sshtunnel#147]
Hi!

I'm playing around with your awesome library and wanted to ask if there's any easy way to keep the tunnel open in the background. I'm trying to have a simple CLI with `open` ans `close` subcommands for multiple different databases.

I'm specifically trying to replicate the `-S` option of `ssh` if that helps - this is what we currently use:
```
# To open
ssh -f -M -N -S /tmp/foobar-socket -L 0.0.0.0:12345:example.com:12345 user@jump.example.com

# To close
ssh -S /tmp/foobar-socket -O exit user@jump.example.com
```

I tried looking through the source code, inspecting the `server._transport.sock` object but with no real progress so far. Any tips would be welcome. Thanks!

**Comment by mdavis-xyz** [comment]
The `.start()` call is non-blocking. It's in the background automatically.

**Comment by pawelad** [comment]
Thanks! I'll give it a try and come back if I encounter any issues.
