### ISSUE TITLE
How to support multiple ssh？

### ISSUE THREAD

**Issue by SirCYong** [pahaz/sshtunnel#151]
problem：
1、localhost： 192.168.22.98
2、gateway： 192.168.22.6
3、destination ： 116.XX.XX.2
I want to connect to the target machine locally. What is the solution?
I want to use code to achieve

**Comment by fernandezcuesta** [comment]
Hi, this is not a Q&A site, please refer to [stackoverflow](https://stackoverflow.com/) or have a look at the [examples in the documentation](https://sshtunnel.readthedocs.io/en/latest/#usage-examples).
