### ISSUE TITLE
Tests OOM and 100% utilization of all cores

### ISSUE THREAD

**Issue by titanofold** [pahaz/sshtunnel#153]
Tests are now failing on Gentoo. Despite the reputation, no patches have been applied to this package, and tests were previously succeeding when I first added it to our repository.

This is as far as the output gets for me:
> platform linux2 -- Python 2.7.15, pytest-4.1.0, py-1.7.0, pluggy-0.8.0
> rootdir: /var/tmp/portage/dev-python/sshtunnel-0.1.4-r1/work/sshtunnel-0.1.4, inifile:
> plugins: xdist-1.25.0, forked-0.2, cov-2.6.1
> gw0 I / gw1 I / gw2 I / gw3 I
> gw0 [50] / gw1 [50] / gw2 [50] / gw3 [50]

After a few seconds, all the cores on my machine get pegged to 100% utilization and the memory gets consumed at a fairly steady rate of ~200 MiBs per second. Eventually, it gets OOM killed.

I made all the platforms and plugin versions listed be the same on my system as those used by CircleCI. I'm not sure where to look next.

Related Gentoo Bug: https://bugs.gentoo.org/683774

**Comment by fernandezcuesta** [comment]
Closing this, since [referenced issue](https://bugs.gentoo.org/683774) is closed and marked as fixed.
