### ISSUE TITLE
Transport hard-coded for IPv4 (no IPv6 support)

### ISSUE THREAD

**Issue by jaraco** [pahaz/sshtunnel#157]
Attempting to connect to an IPv6-only host fails with this error:

```
$ python -c "from sshtunnel import SSHTunnelForwarder; server = SSHTunnelForwarder('myipv6host.example.com', remote_bind_address=('localhost', 8080)); server.start()"                                                     
2019-09-13 14:31:23,039| ERROR   | Could not resolve IP address for myipv6host.example.com, aborting!
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/jaraco/code/public/sshtunnel/sshtunnel.py", line 1294, in start
    reason='Could not establish session to SSH gateway')
  File "/Users/jaraco/code/public/sshtunnel/sshtunnel.py", line 1100, in _raise
    raise exception(reason)
sshtunnel.BaseSSHTunnelForwarderError: Could not establish session to SSH gateway
```

I suspect that's because the [transport is hard-coded for IPv4](https://github.com/pahaz/sshtunnel/blob/397ee78851bdd36d0c11cef319a9f55dd7eb115d/sshtunnel.py#L1114).

It would be nice if the tunnel could connect to an IPv6 host (and prefer that transport based on the results from `getaddrinfo`).

**Comment by fernandezcuesta** [comment]
Did you try first creating an ipv6 socket and pass (`ssh_proxy` parameter) it during tunnel initialisation?

**Comment by V0idk** [comment]
hey,does it support ipv6?

**Comment by V0idk** [comment]
well
it support 

sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
pass to ssh_proxy

**Comment by AceScottie** [comment]
As a quick fix for this i added a try/except case [here.(https://github.com/pahaz/sshtunnel/blob/397ee78851bdd36d0c11cef319a9f55dd7eb115d/sshtunnel.py#L1117).

```
try:
   _socket.connect((self.ssh_host, self.ssh_port)) 
   except:
     try:
       _socket = socket.socket(socket.AF_INET6, socket.SOCK_STREAM)
       _socket.connect((self.ssh_host, self.ssh_port))
     except:
       raise
```

This should be re-writtent to auto switch depending on the style of the server address being used since you already have the check_address funciton.

**Comment by akshay-joshi** [comment]
Hi All

Waiting for IPv6 support. I am using **SSHTunnelForwarder** call to create SSH Tunnel. Is there any roadmap for this feature? When will it be available?
