### ISSUE TITLE
User private keys are not found in default directory

### ISSUE THREAD

**Issue by mapio** [pahaz/sshtunnel#161]
This line of code

https://github.com/pahaz/sshtunnel/blob/bd4ae32344a3a68ce27b1ad27c992687613b3182/sshtunnel.py#L1021

prevents the `or` at

https://github.com/pahaz/sshtunnel/blob/bd4ae32344a3a68ce27b1ad27c992687613b3182/sshtunnel.py#L1026

to kick in and allow for `DEFAULT_SSH_DIRECTORY` to be searched. With the result that no keys are found even when there are plenty!

**Comment by fernandezcuesta** [comment]
> [] == None
False

**Comment by mapio** [comment]
> the problem is the default at
> `__init__` which should be set to an empty list

This is a really bad idea. Mutable objects (such as list) should never be used as default arguments. See https://docs.python-guide.org/writing/gotchas/#mutable-default-arguments for details.

**Comment by fernandezcuesta** [comment]
Ok so start by doing a pull request. That is really a good idea.

**Comment by pahaz** [comment]
@mapio you are right. But do you have any related problems with that? 
It's better to just remove this unreachable code.

**Comment by mapio** [comment]
I'm not sure I get @pahaz question.

If "that" refers to the reported bug, yes: I've a situation where there are plenty of ssh keys, but they are not found.

It "that" refers to using an empty list (or any other mutable object) as a default argument: no, I've not encountered an issue using the code as it is now, but introducing such a change paves the way to possibly un-debuggable errors in the future.

I'm not also sure about @fernandezcuesta comment. Do you mean that I should open a PR? I'm no expert in your code base, so I think it's more reasonable for me to report a bug (and possibly commenting on a proposed bad solution) than to modify your code.

If bug reporting is not enough, consider adding to your contribution guidelines that a bug report without an accompanying pull request is not well received.

**Comment by fernandezcuesta** [comment]
Well honestly I would prefer a PR rather than rude comments in most situations.
Anyway thanks for your heads up. Contribution guidelines will be revised to avoid such unpleasant situations.

**Comment by mapio** [comment]
I did not intend to be rude. To what of my comments you refer? The one where I say that a proposed fix is (and indeed is) a really bad idea?

**Comment by fernandezcuesta** [comment]
The fact that you say something (in the context of a conversation) is a
"really" bad idea doesn't help at all.
A proposal of how to fix it does (either by submitting a PR or giving an
idea in the comments).
Being pedantic and insisting on what is a good or bad idea won't help for
an eventual fix though.

**Comment by pahaz** [comment]
I also have a problem with key findings on Ubuntu.

**Comment by mapio** [comment]
Have you read my comment? 

I've provided a link (https://docs.python-guide.org/writing/gotchas/#mutable-default-arguments) that explains why the proposed fix is a bad idea and how one can do better.

I'm really surprised by your attitude. I've reported a bug, commented on a bad proposed fix (providing a link to an extensive and clear explanation of why the proposed fix is bad) and after one year, out of the blue you attack me saying that I'm pedantic.

Do you think that ignoring a bug report for a whole year and then attacking the user who reported it, moreover providing documented comments in the conversation, will motivate other users to report bug and contribute?

**Comment by fernandezcuesta** [comment]
And this attitude is being pedantic.
I was able to understand your issue first time you said that my
(preliminary, from a comment) idea was REALLY bad. There are different ways
to express that. Omitting the aforementioned word is a good start.
Repeating the same sentence and raising the tone will only underline what I
said before.

Btw complaining about 1y delay for a single loc change is understandable
but this is all done in a best effort in our spare (or spare-spare) time.

Peace

**Comment by pahaz** [comment]
> Do you think that ignoring a bug report for a whole year

It is quite strange that there is only one bug report on this issue. I think that is why this problem was not given the necessary attention.

**Comment by mapio** [comment]
Maybe that's the reason. Notice that 11 out of 15 issues that are still open today date back to 2019, 2018 and 2017.
