### ISSUE TITLE
Hangs on python 3.7

### ISSUE THREAD

**Issue by carkar7** [pahaz/sshtunnel#167]
Currently unable to establish connection on python 3.7. Are there plans to update this?

**Comment by ortenburger** [comment]
perfect error description -- establishes connections fine for me on Python 3.7.4

**Comment by dduraipandian** [comment]
It is not working on 3.7.4. I have set up the environment. It still hangs.

**Comment by pahaz** [comment]
Could you please provide more details. Your OS version and `pip freeze` information.
