### ISSUE TITLE
Connection reset when there is more than ~300 ms of latency

### ISSUE THREAD

**Issue by nickodell** [pahaz/sshtunnel#171]
**OS:** Ubuntu 18.04.3 (LTS) x64
**Version:** sshtunnel 0.1.5

We've been having a problem for some time where a developer will remote in, and get an error when they attempt to access a database. The error looks like this:

```
ERROR | Could not establish connection from ('127.0.0.1', 64998 to remote side of the tunnel
{traceback}
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2013, 'Lost connection to MySQL server during query')
(Background on the error at: http://sqlalche.me/e/e3q8)
```

The error happens about 10-20% of the time.

However, I don't think the database is responsible. The reason for that is that I've tried tunneling other kinds of traffic, such as a TCP echo server, and an HTTP server, and those fail too.

# Detailed Description

I've created a reproducer program which creates an SSH tunnel, and loads a webpage over that tunnel. The reproducer triggers the error 100% of the time. If you run the reproducer, you'll get errors that look like this:

```
2019-12-21 01:18:22,843| ERROR   | Could not establish connection from ('127.0.0.1', 38701) to remote side of the tunnel
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1346, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1346, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cadconnection2.py", line 47, in <module>
    tunnel_test()
  File "cadconnection2.py", line 32, in tunnel_test
    response = requests.get('http://127.0.0.1:%d/' % tunnel.local_bind_port)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 520, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 630, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
```

However, if you take away the latency, the errors stop happening.

# Reproduction

I have created a minimal, reproducible testcase, which works on Linux. Essentially, there are four steps to triggering this bug:

 1. Run HTTP server locally.
 2. Create SSH key so that current user can log in on SSH on localhost
 3. Artificially create latency.
 4. Run the reproducer program.

These steps were tested on Ubuntu 18.04.3 (LTS) x64, on a fresh VM from DigitalOcean.

## Run HTTP server locally

Start a screen:

    screen -S httpserver

Create an HTML file:

    echo "Hello, world!" > index.html

Run a HTTP server on port 8000:

    python3 -m http.server --bind 127.0.0.1 8000

Detach from the screen by pressing Ctrl-A D.

## Create SSH key

Create an SSH key so that you can SSH into your own system:

    ssh-keygen

Add this key to your authorized_keys:

    cat .ssh/id_rsa.pub >> .ssh/authorized_keys

Check that you can ssh to yourself:

    ssh localhost

(To be clear, this problem still occurs when SSHing from one host to another. The reproduction instructions use one host for the sake of simplicity.)

## Artificially create latency

Use the `tc` (traffic control) command to add latency to all packets on the loopback interface:

    sudo tc qdisc add dev lo root netem delay 300ms

(You can remove this rule with `sudo tc qdisc del dev lo root netem`, or by rebooting.)

This problem can also be observed by using an Internet connection with lots of latency, like 4G tethering.

## Run the reproducer program

The program depends on the sshtunnel and requests packages. (I am using `sshtunnel==0.1.5` and `requests==2.18.4`, though I don't think the precise version of the requests package matters.)

The program creates a tunnel pointing at the local web server. Using the tunnel, it requests a webpage from that server. If that succeeds, it closes the tunnel. It does this 10 times, and prints out a number from 0 to 1 representing the proportion of times it succeeded.

Here is the program:

```
import os
from sshtunnel import open_tunnel
import time
import requests
import logging
import traceback

def tunnel_test():
    print('Starting SSH server...')
    with open_tunnel(
        ('127.0.0.1', 22),
        ssh_username='root',
        remote_bind_address=('127.0.0.1', 8000),
        ssh_pkey=os.path.expanduser('~/.ssh/id_rsa'),
        # debug_level=logging.DEBUG
    ) as tunnel:
        # tunnel.start()
        print('Success.')
        print('Waiting...'); time.sleep(0.2); print('#')
        # print('Waiting...'); time.sleep(1); print('#')
        response = requests.get('http://127.0.0.1:%d/' % tunnel.local_bind_port)
        assert response.status_code == 200
        # assert response.content == b'Hello, world!\n'
        print(response.content)
    print('Test successful.')


if __name__ == '__main__':
    # entry point for testing
    trials = 10
    successes = 0
    for i in range(trials):
        print("Iteration: %d" % i)
        success = True
        try:
            tunnel_test()
        except Exception as exc:
            print(traceback.format_exc())
            print(exc)
            success = False
        if success:
            successes += 1
        time.sleep(0.1)
    print("Success rate: %.02f" % (successes / trials))
    # db.close()
```

Running this program has a perfect success rate when no latency is applied. However, when I use the command `sudo tc qdisc add dev lo root netem delay 300ms` to add latency, 100% of the connections fail. If you decrease the delay, the connections will sometimes succeed.

(Above, you'll notice that I have the line `tunnel.start()` commented out. I am unclear from reading the documentation whether this is nessesary when using a `with` statement. I would appreciate clarification on this.)

# Workaround

If you use `time.sleep(1)`, that seems to fix the problem for the case where there is 300 ms of latency. However, if you turn up the latency, you will have the same problem again.

**Comment by arikfr** [comment]
> If you use time.sleep(1), that seems to fix the problem for the case where there is 300 ms of latency. However, if you turn up the latency, you will have the same problem again.

If you use it where? Instead of the `time.sleep(0.1` between loop iterations?

**Comment by pahaz** [comment]
I'm trying to reproduce it on `sshtunnel==0.3.0`. And I also have an error related to `TUNNEL_TIMEOUT`. 
I added `TUNNEL_TIMEOUT = 10.0`, and it solves all timeout errors. 

It looks like a typical problem. I've changed the default TUNNEL_TIMEOUT to 10.0. It'll be `0.3.1`

My code version:

```
import os
from sshtunnel import open_tunnel
import time
import requests
import logging
import traceback
import sshtunnel

sshtunnel.TUNNEL_TIMEOUT = 10.0

sshtunnel.DEFAULT_LOGLEVEL = 1
logging.basicConfig(filename='example.log', filemode='w', level=sshtunnel.DEFAULT_LOGLEVEL)
logging.warning('Start example! v %s', sshtunnel.__version__)

def tunnel_test():
    print('Starting SSH server...')
    with open_tunnel(
        ('127.0.0.1', 22),
        ssh_username='root',
        ssh_pkey='~/.ssh/id_rsa',
        remote_bind_address=('127.0.0.1', 8000),
    ) as tunnel:
        print('Success.')
        print('Waiting...'); time.sleep(0.2); print('#')
        response = requests.get('http://127.0.0.1:%d/' % tunnel.local_bind_port)
        assert response.status_code == 200
        print(response.content)
    print('Test successful.')


if __name__ == '__main__':
    # entry point for testing
    trials = 10
    successes = 0
    for i in range(trials):
        print("Iteration: %d" % i)
        success = True
        try:
            tunnel_test()
        except Exception as exc:
            print(traceback.format_exc())
            print(exc)
            success = False
        if success:
            successes += 1
        time.sleep(0.1)
    print("Success rate: %.02f" % (successes / trials))
```

**Comment by pahaz** [comment]
Could you please run your code again with `sshtunnel==0.3.1` ?

**Comment by pahaz** [comment]
If anyone still has any problem feel free to open a new issue.
