### ISSUE TITLE
SSHTunnelForwarder closing deadlocks if tunnel leads to self and a connection is left open 

### ISSUE THREAD

**Issue by chedatomasz** [pahaz/sshtunnel#173]
This is a bit of a heisenbug.
If I open a tunnel on my laptop from localhost:65000 to dbserver:1521 through server jumpserv, and then open a connection through it (in my case it was cx_Oracle accessing dbserver), closing the SSHTunnelForwarder without closing the dbserver connection prior works fine - the connection drops and the closing finishes.
However, if the same tunnel is opened on jumpserv, from localhost:6500 to server dbserver:1521 through server jumpserv, and then I open the same connection through it, closing the SSHTunnelForwarder without closing the dbserver connection prior leads to a deadlock.
This can lead to strange behaviour, as the same code works fine when executed on one machine and deadlocks on another.
If you'd like, I can try to provide minimal code samples.

**Comment by BuckAMayzing** [comment]
This pointed me in the right direction to discover why tunneling with SQLAlchemy was deadlocking on me. If a `session.close()` is forgotten, this deadlock can pop up. It seems possible that this may be the underlying cause of a few other issues, such as #99 and #162. To workaround, I had to disable connection pooling for the SQLAlchemy engine and make sure all sessions were closed prior to tearing down the tunnel.

**Comment by V0idk** [comment]
I think this is not deadlock,  we should always close all connections before tunnel stop,  because every connections is corresponding to a thread, thread don't quit if you don't close connections

**Comment by sapientderek** [comment]
> This pointed me in the right direction to discover why tunneling with SQLAlchemy was deadlocking on me. If a `session.close()` is forgotten, this deadlock can pop up. It seems possible that this may be the underlying cause of a few other issues, such as #99 and #162. To workaround, I had to disable connection pooling for the SQLAlchemy engine and make sure all sessions were closed prior to tearing down the tunnel.

@BuckAMayzing Thank you for this work around. I'd been trying to find a solution all morning.

**Comment by sapientderek** [comment]
I dug into this a bit more and found the error is 
`/usr/local/lib/python3.7/site-packages/sshtunnel.py in _stop_transport(self)
   1407                 self.logger.info('Shutting down tunnel {0}'.format(tunnel))
   1408                 _srv.shutdown()
-> 1409             _srv.server_close()
   1410             # clean up the UNIX domain socket if we're using one
   1411             if isinstance(_srv, _UnixStreamForwardServer):`

In socketserver's docs it says:

> Changed in version 3.7: socketserver.ForkingMixIn.server_close() and socketserver.ThreadingMixIn.server_close() now waits until all child processes and non-daemonic threads complete. Add a new socketserver.ForkingMixIn.block_on_close class attribute to opt-in for the pre-3.7 behaviour.

The simplest solution is probably setting `_srv.block_on_close=True`.

**Comment by carkar7** [comment]
> This pointed me in the right direction to discover why tunneling with SQLAlchemy was deadlocking on me. If a `session.close()` is forgotten, this deadlock can pop up. It seems possible that this may be the underlying cause of a few other issues, such as #99 and #162. To workaround, I had to disable connection pooling for the SQLAlchemy engine and make sure all sessions were closed prior to tearing down the tunnel.

Can you please elaborate on how you disabled connection pooling? I've been unable to connect to a MySQL DB  on python 3.7 using SQLalchemy, and I want to see if this might be why. Im able to connect with python 3.6 no problem. The function I use is:

```
def query(q, params= None):
    "127.0.0.1 is local host"
    with SSHTunnelForwarder(
        (host, 22),
        ssh_username=ssh_username,
        ssh_password=ssh_private_key,
        remote_bind_address=(localhost, 3306)
    ) as server:
        conn_string=f'mysql+pymysql://{user}:{password}'+'@'+'127.0.0.1:'+f'{server.local_bind_port}/{database}'
        conn = create_engine(conn_string)
        if params == None:
            return pd.read_sql_query(q, conn)
        else:
            return pd.read_sql_query(q, conn, params=params)
```

On 3.7, I hang forever and after a keyboard interrupt, i get the following error message:

```
KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-2-4d3a2ec99303> in <module>
      1 query("""
      2 select * from sales_flat_order LIMIT 10
----> 3 """)

~/Documents/my_packages/c38_db_connect.py in query(q, params)
     41             return pd.read_sql_query(q, conn)
     42         else:
---> 43             return pd.read_sql_query(q, conn, params=params)
     44 
     45 

~/anaconda3/envs/tf/lib/python3.7/site-packages/sshtunnel-0.1.5-py3.7.egg/sshtunnel.py in __exit__(self, *args)
   1556 
   1557     def __exit__(self, *args):
-> 1558         self._stop_transport()
   1559 
   1560 

~/anaconda3/envs/tf/lib/python3.7/site-packages/sshtunnel-0.1.5-py3.7.egg/sshtunnel.py in _stop_transport(self)
   1407                 self.logger.info('Shutting down tunnel {0}'.format(tunnel))
   1408                 _srv.shutdown()
-> 1409             _srv.server_close()
   1410             # clean up the UNIX domain socket if we're using one
   1411             if isinstance(_srv, _UnixStreamForwardServer):

~/anaconda3/envs/tf/lib/python3.7/socketserver.py in server_close(self)
    672             if threads:
    673                 for thread in threads:
--> 674                     thread.join()
    675 
    676 

~/anaconda3/envs/tf/lib/python3.7/threading.py in join(self, timeout)
   1042 
   1043         if timeout is None:
-> 1044             self._wait_for_tstate_lock()
   1045         else:
   1046             # the behavior of a negative timeout isn't documented, but

~/anaconda3/envs/tf/lib/python3.7/threading.py in _wait_for_tstate_lock(self, block, timeout)
   1058         if lock is None:  # already determined that the C code is done
   1059             assert self._is_stopped
-> 1060         elif lock.acquire(block, timeout):
   1061             lock.release()
   1062             self._stop()

KeyboardInterrupt: 
```

**Comment by blakev** [comment]
I'm establishing an `SSHTunnelForwarder` in a ThreadPoolExecutor for asyncio-ness. When I called `.stop()` it would hang the application too.

I solved this by running `.stop()` in a thread pool as well, and now it shuts down fine.

Maybe spawning a thread where `target=tunnel.stop` might help.

**Comment by pahaz** [comment]
Yes, currently we are always waiting until closing all connections before the stop.
We assume that you know better how to stop your connections before stop the tunnel.

Is this a problem for anyone?

**Comment by pahaz** [comment]
We have an update. You can use `.stop(force=True)` (new in 0.2.2) for force closing active connections.

**Comment by pahaz** [comment]
`sshtunnel==0.3.0` is released! if you still have any problem feel free to reopen the issue or open a new one.
