### ISSUE TITLE
KeyboardInterrupt causes None to be bound to context manager target

### ISSUE THREAD

**Issue by chasewalden** [pahaz/sshtunnel#174]
When using `SSHTunnelForwarder` as a context manager, there is an edge case where the user can raise a `KeyboardInterrupt` while inside the `__enter__()` method. 

There is already a try-except block that catches this, but an unintended side-effect is that the exception is suppressed entirely, resulting in the context manager's target binding to be `None` and the child block being executed. 

It makes sense why the exception is being caught in `__enter__()`, but the exception should not be suppressed. The exception should be re-raised after calling `self.__exit__()` to prevent the user from receiving a `None` value inside the context.

On a related note, there are probably other exceptions that could be thrown during `self.start()`. Maybe it makes sense for the `except` clause to catch any exception, call `__exit__()` and re-raise. 

```python
def __enter__(self):
    try:
        self.start()
        return self
    except KeyboardInterrupt: # or maybe just `except:`
        self.__exit__()
        raise
```

To reproduce, just try to connect to a host with high latency. While it is connecting, press Ctrl-C

```python
with SSHTunnelForwarder( ... ) as tunnel:
        print(tunnel)
        print(tunnel.is_alive)
```

Results in:

```
^CNone
Traceback (most recent call last):
  File "src/main.py", line 13, in main
    print(tunnel.is_alive)
AttributeError: 'NoneType' object has no attribute 'is_alive'
```

**Comment by pahaz** [comment]
`sshtunnel==0.3.0` is released! if you still have any problem feel free to reopen the issue or open a new one.
