### ISSUE TITLE
Passing a non-root logger without handlers fails to log some messages

### ISSUE THREAD

**Issue by jdacruzcost** [pahaz/sshtunnel#175]
Hi All,
First, great work on this project!

In https://github.com/pahaz/sshtunnel/blob/master/sshtunnel.py#L195, this assumes that the logger that we pass has handlers.

In my app, I create a Logger per Class and inherits everything (formatter, handlers. etc...) from the root logger. In my way, I cannot see messages from sshtunnel but I can see paramiko's messages.

I use:
Class -> __init__:
self.logger = logging.getLogger(self.__class__.__qualname__)

Class -> method:
sshtunnel.open_tunnel(
    ... ,
    logger = self.logger,
    debug_level = self.logger.getEffectiveLevel()
)

Dunno if this will help: https://stackoverflow.com/questions/3630774/logging-remove-inspect-modify-handlers-configured-by-fileconfig

**Comment by jdacruzcost** [comment]
Oh, forgot to add this bit. If I comment out from L195 to L200, logging works perfectly.

**Comment by pahaz** [comment]
You can use a `sshtunnel.SSHTunnelForwarder` name for your logger and customize it as you want.
