### ISSUE TITLE
Local tunnel to remote without binding?

### ISSUE THREAD

**Issue by alexge233** [pahaz/sshtunnel#178]
Hi, I'm not sure this package can achieve what I want (which is pretty trivial compared to the examples), I'm only interested in opening a local port which forwards my connections to a remote (socks 5). Not interested in opening a remote port.
Sort of like this:
```
 ssh -D 9000 -N -o PubkeyAuthentication=no user@example.com
```
Is this possible? Every time I try without `remote_bind_address` it fails to start.

**Comment by pahaz** [comment]
It's dynamic port forwarding. At the moment we have just a PR for that feature here: https://github.com/pahaz/sshtunnel/pull/93

Duplicate: https://github.com/pahaz/sshtunnel/issues/87

**Comment by alexge233** [comment]
Thanks @pahaz feel free to close this
