### ISSUE TITLE
When using .start(), code continues to run before connection is established

### ISSUE THREAD

**Issue by Keagel** [pahaz/sshtunnel#185]
I was wondering why my SSH tunnel within Python wouldn't work when manually starting it with the CLI worked, and I stumbled upon [this StackOverflow](https://stackoverflow.com/a/39946827/8349136) where the user mentions that adding `sleep(1)` after the `start()` method worked. I just tried this and indeed it works.

Is there a more elegant/less hackish way to wait for the tunnel to have started without using `with`?

**Comment by fernandezcuesta** [comment]
You can set `skip_tunnel_checkup` to false, or use check_tunnels(). Refer
to [API documentation](
https://sshtunnel.readthedocs.io/en/latest/?badge=latest#api) for further
details.
<https://sshtunnel.readthedocs.io/en/latest/?badge=latest#sshtunnel.SSHTunnelForwarder.skip_tunnel_checkup>
Anyway, using context manager is IMHO the less hacky/cleanest way to
proceed.

**Comment by Keagel** [comment]
Neither of the two solutions work for me it seems so I will have to use the context manager. Thanks anyways!

**Comment by pahaz** [comment]
Yes, it's a typical problem. I think there is not a part of the sshtunnel. We can't truly understand that database is ready for execution queries. It's better to use sleep or wait until you successfully execute a query like `select 1+1`.

**Comment by pahaz** [comment]
I'll close it. If you still have any problem. Feel free to open new or reopen this issue
