### ISSUE TITLE
Is sshtunnel can be used for AWS S3?

### ISSUE THREAD

**Issue by vekee** [pahaz/sshtunnel#187]
Is sshtunnel can be used for AWS S3?
In this case:
client→tunnel1→tunnel2→S3

I have used sshtunnel connected to  AWS RDS, but how to set for connect to S3?
client→tunnel1→tunnel2→RDS

Can the remote_bind_address set for all hosts?

I want use target_host  to be set in my script, not local_bind_address, can i do it with set local_bind_address?

**Comment by pahaz** [comment]
I think you can do it. For example, you have HOST1, HOST2 and HOST3 like so:
```
----------------------------------------------------------------------



                       |                         |               
-------------+         |   +----------+          |  +----------+ 
    LOCAL    |         |   |  REMOTE  | :22 SSH  |  |  REMOTE  |   
    CLIENT   | <= SSH ===> |  SERVER1 | <= SSH ===> |  SERVER2 | ==> S3
-------------+         |   +----------+          |  +----------+ 
                       |                         |               
                      FIREWALLS (only port 22 is open)

----------------------------------------------------------------------
```

1) you create 1st tunnel from localhost to SERVER2 throw SERVER1 and get a `local_bind_address1`
2) you create 2nd tunnel from localhost to S3 throw `local_bind_address1`

**Comment by vekee** [comment]
thank you for your answer
i have tried that, but S3 has a gateway,  not succeeded.
so it will be access by that way:
client→tunnel1→tunnel2→ S3's gateway →S3

**Comment by vekee** [comment]
> I think you can do it. For example, you have HOST1, HOST2 and S3 like so:
> 
> ```
> ----------------------------------------------------------------------
> 
> 
> 
>                        |                         |               
> -------------+         |   +----------+          |  +----------+ 
>     LOCAL    |         |   |  REMOTE  | :22 SSH  |  |  REMOTE  |   
>     CLIENT   | <= SSH ===> |  SERVER1 | <= SSH ===> |  SERVER2 | ==> S3
> -------------+         |   +----------+          |  +----------+ 
>                        |                         |               
>                       FIREWALLS (only port 22 is open)
> 
> ----------------------------------------------------------------------
> ```
> 
> 1. you create 1st tunnel from localhost to SERVER2 throw SERVER1 and get a `local_bind_address1`
> 2. you create 2nd tunnel from localhost to S3 throw `local_bind_address1`

**Comment by pahaz** [comment]
You can look at https://github.com/pahaz/sshtunnel#example-4
