### ISSUE TITLE
How to automatically reconnection when SSHtunnel is disconnected  Or stay connected

### ISSUE THREAD

**Issue by yuemengrui** [pahaz/sshtunnel#188]
```
class Config(object):
    ssh_host = "***.***.***.***" 
    ssh_user = "root"  
    ssh_password = "xcdfbbrbbbr"  
    ssh_port = 22

    forwarding_server = sshtunnel.SSHTunnelForwarder(
        (ssh_host, ssh_port),
        ssh_username=ssh_user,
        ssh_password=ssh_password,
        remote_bind_address=('localhost', 3306)
    )
    forwarding_server.start()
    local_port = forwarding_server.local_bind_port
 
    SQLALCHEMY_DATABASE_URI = "mysql://root:sdergrgd@127.0.0.1:{}/ai".format(local_port)
    SQLALCHEMY_TRACK_MODIFICATIONS = False
```

I used SSHtunnels in the flask project, When the project starts, it can be used normally，but, After a period of time, the SSHtunnel will be disconnected, resulting in MySQL connection failure。

ERROR:sshtunnel.SSHTunnelForwarder:Could not establish connection from ('127.0.0.1', 42509) to remote side of the tunnel
pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query')

**Comment by pahaz** [comment]
There are two cases:
 1) the end side of the tunnel remote side is down for a while: in this case, everything will work fine
 2) your ssh server close/terminate the ssh session: we don't detect it, and not reconnecting

I think you got the case 2. We will fix it in a future release

**Comment by pahaz** [comment]
As a workaround, you can use:

**Comment by pahaz** [comment]
As a workaround, you can try `tunnel.restart()` in case of `if not tunnel.is_active`:

```
import logging
import sshtunnel
from sshtunnel import HandlerSSHTunnelForwarderError, SSHTunnelForwarder

sshtunnel.DEFAULT_LOGLEVEL = 1
logging.basicConfig(filename='example.log', filemode='w', level=sshtunnel.DEFAULT_LOGLEVEL)
logging.warning('Start example! sshtunnel v%s', sshtunnel.__version__)

tunnel = SSHTunnelForwarder(
    ('165.22.65.44', 22),
    ssh_username='root',
    ssh_pkey='~/.ssh/id_rsa',
    remote_bind_address=('127.0.0.1', 1500),
    local_bind_address=('127.0.0.1', 53826),
)

tunnel.start()
try:
    i = 1
    while True:
        time.sleep(1)
        if i % 10 == 0:
            if not tunnel.is_active:
                print('SSH Tunnel is DOWN! restarting ...')
                tunnel.restart()
        i += 1
finall:
    tunnel.stop()
```

**Comment by yuemengrui** [comment]
think you!  I've solved this problem，I used this parameter : set_keepalive=5.0

**Comment by f1nality** [comment]
Hi @pahaz so it was not implemented yet?
