### ISSUE TITLE
error connecting

### ISSUE THREAD

**Issue by ZUNbado** [pahaz/sshtunnel#21]
Hi,

There is my code:

    from sshtunnel import SSHTunnelForwarder

    server = SSHTunnelForwarder(
            ssh_address=(config.SSH_HOST,config.SSH_PORT),
            ssh_username=config.SSH_USER,
            ssh_password=config.SSH_PASSWORD,
            remote_bind_address=(config.SSH_REMOTE_HOST, config.SSH_REMOTE_PORT)
            )
    server.start()
    print server.local_bind_port

And when execute them, i'm receive this error

  File "tunel.py", line 34, in <module>
    server.start()
  File "/usr/local/lib/python2.7/dist-packages/sshtunnel.py", line 664, in start
    for _srv in self._server_list
TypeError: __init__() got an unexpected keyword argument 'daemon'

Can you help me?

**Comment by balramr** [comment]
I have the same issue. [This recent commit](https://github.com/pahaz/sshtunnel/commit/0c7cd4c890b0ca08ad266bbad94684a04e92487f) fixes the problem, but it hasn't made it to a release.

While I can work around it by pulling from git, is there any chance of seeing a release? The current version available on pip is broken for me.

**Comment by pahaz** [comment]
I run your example:
  - Python3 - ok
  - Python2 - ok

My mistake, need update sshtunnel on pypi.

**Comment by pahaz** [comment]
pypi version updated! use: `pip install sshtunnel --upgrade`

I apologize for this problem.
