### ISSUE TITLE
sshtunnel.readthedocs.io is out of date!

### ISSUE THREAD

**Issue by pahaz** [pahaz/sshtunnel#210]
Currently, the sshtunnel.readthedocs.io is not updated by CI. @fernandezcuesta what do you think?

**Comment by fernandezcuesta** [comment]
Hi there,
currently there's no commit webhook in place (lack of permissions in gh repo).
Have a look at the [webhook howto](https://docs.readthedocs.io/en/latest/webhooks.html).

**Comment by pahaz** [comment]
Yeee it's done !
