### ISSUE TITLE
Default loglevel or DEBUG is too high, annoying

### ISSUE THREAD

**Issue by lewisthompson** [pahaz/sshtunnel#22]
Suggest changing DEBUG -> CRITICAL for general sanity.

```python
DEFAULT_LOGLEVEL = 'CRITICAL'  # Default level for logging, if no logger passed
```

**Comment by fernandezcuesta** [comment]
In my opinion INFO is good enough (verbose, while not annoying) for normal usage. I agree DEBUG may be too much (except for the developer).

**Comment by pahaz** [comment]
I have created new issuse for this problem.

**Comment by pahaz** [comment]
Please reopen if this solution does not solve your problem.
