### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Ed25519Key'

### ISSUE THREAD

**Issue by pahaz** [pahaz/sshtunnel#220]
It looks like some of our users have a problem with `paramiko.Ed25519Key`:
https://stackoverflow.com/questions/52012853/pgadmin4-error-module-paramiko-has-no-attribute-ed25519key

Ci is also failing: https://github.com/pahaz/sshtunnel/runs/1417654323?check_suite_focus=true

**Comment by fernandezcuesta** [comment]
That's a problem with paramiko < 2.2 (see [docs](http://docs.paramiko.org/en/stable/api/keys.html#module-paramiko.ed25519key))

**Comment by pahaz** [comment]
Yes, but we can check it on our side. like `if not hasattr(paramiko, 'Ed25519Key'): warn warn warn!`
And don't fail. Because it's not so important for sshtunnel to use `Ed25519Key` if it does not exist.

**Comment by pahaz** [comment]
Or we should increase a required paramiko version here: https://github.com/pahaz/sshtunnel/blob/master/setup.py#L100

**Comment by pahaz** [comment]
I'll fix it in https://github.com/pahaz/sshtunnel/pull/219

**Comment by pahaz** [comment]
It looks like paramiko has some other errors related to pkey. It's better to up the paramiko version and drops old paramiko version support.
