### ISSUE TITLE
Default logger displays ssh password

### ISSUE THREAD

**Issue by xaniasd** [pahaz/sshtunnel#24]
I'm using getpass to allow the user to enter his ssh password on the command-line, before starting the tunnel. However this is then logged in plain text by the logger (DEBUG level). I can avoid this by enforcing a higher logging level but it would be safer not displaying it at all by default.

**Comment by fernandezcuesta** [comment]
my suggestion: create a develop branch and keep DEBUG loglevel as default. On master, set default loglevel to INFO as explained in #22

**Comment by pahaz** [comment]
https://github.com/pahaz/sshtunnel/commit/867854447c9d0e2efba3fa5358db44dcb906e0eb - fixed
