### ISSUE TITLE
Add option to not read ~/.ssh/config & pass private key through the API

### ISSUE THREAD

**Issue by eudoxos** [pahaz/sshtunnel#28]
This would be useful when running unit tests so that all data are in the test suite. This entails passing `ssh_private_key` as str/bytes in `__init__`. Are you open to pull requests if I do that? Thx.

**Comment by pahaz** [comment]
Yes

**Comment by pahaz** [comment]
Do you have any time to do this?

**Comment by fernandezcuesta** [comment]
Fixed with #40 and #43.

**Comment by eudoxos** [comment]
Sorry, I was offline for a longer time. Good to see @fernandezcuesta stepped in, thanks!

**Comment by pahaz** [comment]
Great news! Thanks!
