### ISSUE TITLE
Unable to make connection to the database server when sslmode is "verify-full".

### ISSUE THREAD

**Issue by akshay-joshi** [pahaz/sshtunnel#285]
**SSH Tunnel Setup:**
1) **Fedora 37** (VM in NAT mode): PostgreSQL is installed and SSL mode is on. Created 3 certificates server.crt, server.key, and root.crt. Given common name as **'akshay.pgadmin'** while creating certificates. 
2) **Mac OSX**: Base machine used for tunnling
3) **Windows 10** (sshtunnel is installed using pip)

**Steps to reproduce:**

- Copy **root.crt** to the client machine (Windows 10).
- Created sshtunnel using command `sshtunnel -L 127.0.0.1:12345 -R akshay.pgadmin:5432 -- <IP address of OSX machine>`
-  In another terminal run psql command to connect to the database server with **sslmode=verify-full** and provide the root certificate. Run the command 
`psql -d "host=akshay.pgadmin hostaddr=127.0.0.1 port=12345 dbname=postgres user=postgres password=adminedb connect_timeout=10 sslmode=verify-full sslrootcert='C:/Users/Akshay Joshi/Desktop/root.crt'"`

It is throwing an error Could not establish connection from local ('127.0.0.1', 12345) to remote ('akshay.pgadmin', 5432) side of the tunnel: open new channel ssh error: ChannelException(2, 'Connect failed')

<img width="1679" alt="Screenshot 2023-10-10 at 6 33 16 PM" src="https://github.com/pahaz/sshtunnel/assets/1632882/5cce4e8c-e30c-49cf-a453-3dee7e672921">

**Note:**: We also make an entry to the **hosts** file for <IP Address of the database server machine>  akshay.pgadmin, still it is not connected. If we use the **IP Address of the database server machine** instead of **'akshay.pgadmin'** while creating the tunnel it works, but the point is we will have to provide the **host=akshay.pgadmin** in the connection string as sslmode is verify-full.

Original Issue in pgAdmin [6770](https://github.com/pgadmin-org/pgadmin4/issues/6770)

**Comment by pahaz** [comment]
It looks like related issues are already closed! with these changes https://github.com/pgadmin-org/pgadmin4/commit/81dcc917476c638ba32807ae9ae7f884b8b9182d 

If you still have some problems reopen this issue
