### ISSUE TITLE
Please add option to set SSH idle timeout.

### ISSUE THREAD

**Issue by pmogren** [pahaz/sshtunnel#29]

**Comment by pahaz** [comment]
Hi! Can you provide more information about your use-case?

**Comment by pmogren** [comment]
In https://github.com/commercehub-oss/watershed we use sshtunnel to forward local ports to service endpoints on an AWS EMR cluster, according to http://docs.aws.amazon.com/ElasticMapReduce/latest/DeveloperGuide/emr-ssh-tunnel-local.html

When the connection sits idle for a while, it silently breaks down. When I finally try to use it again, I get an error. I have not measured how long it takes to break down; probably somewhere between 15 and 60 minutes in this case, but the SSH server configuration could alter that. 

I would like to be able to set ServerAliveInterval, which is a client-side SSH option to heartbeat the connection, so the server does not consider it idle and close it.

**Comment by fernandezcuesta** [comment]
I guess this can be done by enabling keepalive packets on paramiko transport (http://docs.paramiko.org/en/1.15/api/transport.html?highlight=alive#paramiko.transport.Transport.set_keepalive).
As a workaround you may enable ClientAliveInterval/ClientAliveCountMax on OpenSSH servers.

**Comment by pmogren** [comment]
Thank you, I look forward to trying it.

**Comment by nika11** [comment]
I know this issue has been closed few years ago. but is there some parameter we can do to control the timeout?

**Comment by abubelinha** [comment]
Same question.

Shouldn't the issue be still open if the requested feature does not exist yet?
