### ISSUE TITLE
New pip release for ssh_private_key_password

### ISSUE THREAD

**Issue by alourie** [pahaz/sshtunnel#30]
I am using sshtunnel with certificates with passwords. It would be awesome to have a new pip release including the ssh_private_key_password code that was merged 15 days ago.

Thanks.

**Comment by pahaz** [comment]
I want do this on weekend.

**Comment by alourie** [comment]
@pahaz any update for this? Thanks

**Comment by pahaz** [comment]
@alourie yes, 0.0.5 released

**Comment by pahaz** [comment]
@alourie, special for you in 0.0.6 add `-S` argument
