### ISSUE TITLE
Is there a way to make it work with Pageant on Windows ?

### ISSUE THREAD

**Issue by 62mkv** [pahaz/sshtunnel#36]
I could not manage it.. Has anybody tried that ? Which options should be used ? 

I was (seemingly) able to connect to SSH using paramiko with Pageant, but I could not establish working tunnel for MySQL

I can provide more details if anyone is interested.

**Comment by pahaz** [comment]
Try use example from docs: `python -m sshtunnel -U vagrant -P vagrant -L :3306 -R 127.0.0.1:3306 -p 2222 localhost` -- create tunnel to virtualbox mysql

**Comment by 62mkv** [comment]
the issue is I could not use sshtunnel at all without providing either private key either password into constructor SSHTunnelForwarder(...), which i normally should be able to do when using Pageant and private key is loaded into it already

**Comment by fernandezcuesta** [comment]
Maybe this is related to #33, which is now fixed after https://github.com/pahaz/sshtunnel/commit/eeeb1140d295b6b4af8c63b1a5e0f31801880ee6.

**Comment by 62mkv** [comment]
I don't have ~/.ssh/config, and Pageant does not use it. I've tried to modify SSHTunnel.py for using "ssh_agent" mode, but still that did not work, I got errors like OOPS Unexpected argument when I was trying to connect. 

My question was - does SSHTunnel/paramiko support Pageant at all ? May be it does not, that would explain my problem.

**Comment by fernandezcuesta** [comment]
Pageant is the SSH authentication agent for putty whereas sshtunnel is using paramiko as SSH client. None of them call putty AFAIK.
Could you please enlighten a bit when you say the following? 
> I was (seemingly) able to connect to SSH using paramiko with Pageant

**Comment by 62mkv** [comment]
I mean this (see accepted answer): http://stackoverflow.com/questions/8490228/how-to-use-pageant-with-paramiko-on-windows

**Comment by 62mkv** [comment]
It connects successfully but SSHTunnel does not work (I had to patch it though, in order to use allow_agent option)

**Comment by pahaz** [comment]
That the reason of use Pagent? Try to use sshtunnel without Pagent. 

```
C:\Users\pahaz_000>python -m sshtunnel --help
usage: sshtunnel.py [-h] [-U SSH_USERNAME] [-p SSH_PORT] [-P SSH_PASSWORD] -R
                    IP:PORT [IP:PORT ...] [-L [IP:PORT [IP:PORT ...]]]
                    [-k SSH_HOST_KEY] [-K RSA_KEY_FILE] [-t] [-v]
                    ssh_address

sshtunnel

positional arguments:
  ssh_address           SSH server IP address (GW for ssh tunnels)
                        set with "-- ssh_address" if immediately after -R or -L

optional arguments:
  -h, --help            show this help message and exit
  -U SSH_USERNAME, --username SSH_USERNAME
                        SSH server account username
  -p SSH_PORT, --server_port SSH_PORT
                        SSH server TCP port (default: 22)
  -P SSH_PASSWORD, --password SSH_PASSWORD
                        SSH server account password
  -R IP:PORT [IP:PORT ...], --remote_bind_address IP:PORT [IP:PORT ...]
                        Remote bind address sequence: ip_1:port_1 ip_2:port_2 ... ip_n:port_n
                        Equivalent to ssh -Lxxxx:IP_ADDRESS:PORT
                        If omitted, default port is 22.
                        Example: -R 10.10.10.10: 10.10.10.10:5900
  -L [IP:PORT [IP:PORT ...]], --local_bind_address [IP:PORT [IP:PORT ...]]
                        Local bind address sequence: ip_1:port_1 ip_2:port_2 ... ip_n:port_n
                        Equivalent to ssh -LPORT:xxxxxxxxx:xxxx, being the local IP address opt
ional.
                        By default it will listen in all interfaces (0.0.0.0) and choose a rand
om port.
                        Example: -L :40000
  -k SSH_HOST_KEY, --ssh_host_key SSH_HOST_KEY
                        Gateway's host key
  -K RSA_KEY_FILE, --private_key_file RSA_KEY_FILE
                        RSA private key file
  -t, --threaded        Allow concurrent connections to each tunnel
  -v, --verbosity       Increase output verbosity (default: 40)
```

Try use `-K` for key_file.

**Comment by 62mkv** [comment]
the point of using Pageant is to provide a passphrase only once and forget about it. I was able to connect in the end, but having to have passphrase in the script files is vulnerable, and having to provide it manually on each connection is tedious. Thus the question. 

So, sshtunnel does not support such usage so far, am I right ?

**Comment by 62mkv** [comment]
(the thing is pageant is running on my machine almost 100 % of time, so for the most cases I don't even bother with providing key file/passphrase. of course that would be great to have for SSHTunnel s well)

**Comment by fernandezcuesta** [comment]
@62mkv it shhould be fixed now. By setting allow_agent = True (--agent) it will first try to log in using the keys available in the SSH agent, then the authentication methods specified as arguments.
