### ISSUE TITLE
Catch “Could not open connection to gateway”

### ISSUE THREAD

**Issue by whbos** [pahaz/sshtunnel#37]
Every now and then setting up a tunnel using sshtunnel.py fails because the gateway (ssh_host) complains the first time I connect to it. I would like to give it a few retries before giving up:
```
for attempt in range(5):
    try:
        forwarder.start()
    except Exception, e:
        print 'Error (trying again in five seconds):\n' + format(e.message))
        time.sleep(5)
    else:
        break
else:
    print 'Failed to setup a connection to the gateway'
    sys.exit(1)
```
However, the exception is not caught. I took a peek in the sshtunnel.py code and found that the [following][1] code catches the related Paramiko exception:
```
except paramiko.ssh_exception.AuthenticationException:
    self.logger.error('Could not open connection to gateway')
    return
```
Does this make it impossible to catch a 'Could not open connection to gateway' exception?

[1]: https://github.com/pahaz/sshtunnel/blob/94c2bef94b59494a287fe07158baa103efefaab5/sshtunnel.py#L669

**Comment by fernandezcuesta** [comment]
I guess you can still do the following:
```
for attempt in range(5):
    try:
        forwarder.start()
        forwarder._check_is_started()
    except BaseSSHTunnelForwarderError as e:
        print 'Error (trying again in five seconds):\n' + format(e.message))
        time.sleep(5)
    else:
        break
else:
    print 'Failed to setup a connection to the gateway'
    sys.exit(1)
```

**Comment by whbos** [comment]
Hi fernandezcuesta,

Thanks for your quick response.

I spent the last few hours reproducing the actual error but was unable to. It had something to do with the 'SSH banner' but simulating SSH with `nc -l 22` and trying to connect to that fails with Paramiko exception 'SSHException'. And that one I can catch.

Anyways, I'll add `forwarder._check_is_started()` to my code. Thank you!
