### ISSUE TITLE
Provide install instructions

### ISSUE THREAD

**Issue by smaudet** [pahaz/sshtunnel#38]
Wasted a bunch of time wondering why my setup.py install wasn't working, and why setup.py --prefix wasn't recognized. Please provide install instructions within your README.md

**Comment by pahaz** [comment]
Try to use `pip install sshtunnel` or `easy_install -U sshtunnel`.

**Comment by pahaz** [comment]
If you have any arror please attach console output. https://github.com/pahaz/sshtunnel#install
