### ISSUE TITLE
Is there a way to use the private keys loaded in ssh agent ?

### ISSUE THREAD

**Issue by laurrentt** [pahaz/sshtunnel#46]
I had my own implementation of the SSH Forwarder using Paramiko, but yours looks a lot more solid. However it doesn't seem to use the the private keys loaded in my ssh agent (the one you can list with `ssh-add -l`). Is such thing possible in the current version or is this something we would need to develop.

**Comment by fernandezcuesta** [comment]
Hi, AFAIK there is no easy way to do this. If I'm not mistaken you need to establish a session first, then register it with `paramiko.agent.AgentRequestHandler`.
Anyway pull requests are more than welcome :smile:.

**Comment by fernandezcuesta** [comment]
Maybe what you can do is first try to check which key from the agent is valid, then use that one:

    for key in paramiko.Agent().get_keys():
        try:
            transport.auth_publickey(username, key)
            return key
        except paramiko.SSHException:
            pass

**Comment by fernandezcuesta** [comment]
Should be fixed now. By setting `allow_agent = True` (`--agent`) it will first try to log in using the keys available in the SSH agent, then the authentication methods specified as arguments.

**Comment by laurrentt** [comment]
You rock ! I'm going to try it as soon as 0.0.8 is out on pip.

**Comment by fernandezcuesta** [comment]
You may give a try installing from source, if don't want to wait till 0.0.8

**Comment by Ohjeah** [comment]
(self.ssh_password, ssh_private_key) = self._consolidate_auth(
            ssh_password=ssh_password,
            ssh_private_key=ssh_private_key,
            ssh_private_key_password=ssh_private_key_password,
            logger=logger
        )

      self.ssh_private_keys = self.get_keys(key=ssh_private_key,
                                              allow_agent=allow_agent,
                                              logger=self.logger)


If you neither provide ssh_private_key nor ssh_password _consolidate_auth will raise an ValueError before get_keys is called.

**Comment by fernandezcuesta** [comment]
Thanks for pointing this up!

**Comment by tobycheese** [comment]
Is this supposed to still work? I get

`ERROR   | Password is required for key ...ssh/id_rsa`

The demo.py works in this regard, but I was unable to combine it with a working forwarder in reasonable time.
