### ISSUE TITLE
sshtunnel 0.0.8 doesn't work Windows

### ISSUE THREAD

**Issue by pgolec** [pahaz/sshtunnel#49]
Release 0.0.8 won't work on Windows.

Specifically, `socketserver` doesn't expose `UnixStreamServer` on Windows. Since `_UnixStreamForwardServer` inherits from `socketserver.UnixStreamServer`, merely importing `sshtunnel` results in an Exception being raised on Windows.

**Comment by luddwichr** [comment]
Unfortunately, Release 0.0.8.1 it still doesn't work on Windows. I am using Python 3.5.1 (64-Bit) and Paramiko 1.15.3. I am getting the following error message:

    Traceback (most recent call last):
        File "...\test.py", line 2, in <module> from sshtunnel import SSHTunnelForwarder
        File "...\lib\site-packages\sshtunnel.py", line 378, in <module> class _UnixStreamForwardServer(UnixStreamServer, _ForwardServer):
    TypeError: Cannot create a consistent method resolution order (MRO) for bases _ForwardServer, TCPServer

I made the script work by removing lines 57--60 and replacing lines 377-387 with:

```
if os.name == 'posix':
    class _UnixStreamForwardServer(socketserver.UnixStreamServer, _ForwardServer):
        """
        Serve over UNIX domain sockets (does not work on Windows)
        """

        @property
        def local_host(self):
            return None

        @property
        def local_port(self):
            return None
else:
    class _UnixStreamForwardServer(_ForwardServer):
        """
        Serve over UNIX domain sockets (does not work on Windows)
        """

        @property
        def local_host(self):
            return None

        @property
        def local_port(self):
            return None
```
I didn't work myself into the script really, so does this make sense at all? The docstring even says "Serve over UNIX domain sockets (does not work on Windows)", so it might make sense to only define it for Posix-based OSes?

**Comment by fernandezcuesta** [comment]
I see, it's inheriting twice from TCPServer and python3 doesn't like that. Thanks for reporting!
