### ISSUE TITLE
fails to get local interfaces if cannot resolve local hostname

### ISSUE THREAD

**Issue by derwentx** [pahaz/sshtunnel#56]
Hey,
I noticed that for some reason, SSHTunnelForwarder would always throw an exception regardless of the parameters, 

`  socket.gaierror: [Errno 8] nodename nor servname provided, or not known`

it was caused by _get_local_interfaces trying to resolve the local hostname (in my case, Ich) and failing (probably just a bad /etc/hosts file or something, not really sure)

anyway, this caused me a couple of hours of frustration but i eventually figured out that if i replace 

          local_if = socket.gethostbyname_ex(socket.gethostname())[-1]

with 

          try:
            local_if = socket.gethostbyname_ex(socket.gethostname())[-1]
        except:
            local_if = []

it will handle this exception.

I can make a pull request if you like.

**Comment by fernandezcuesta** [comment]
@derwentx thanks for reporting!
The idea here is to get the list of interfaces of the system without further dependencies, please send a PR if you find a more reliable way to achieve it.

**Comment by cassiopaeslemesc** [comment]
hey @derwentx are you on OSX? I submitted a PR today that addresses this issue by appending a ".local" extension, see if that works for you?

**Comment by derwentx** [comment]
Hey @cassiopaeslemesc and @fernandezcuesta ,
Thanks for the fix and the reply!
Yes I am on OSX (probably should have mentioned that, sorry)
It seems that @cassiopaeslemesc has fixed it in their PR, as I can still establish a tunnel even though when i call `socket.gethostbyname()` on my value of `socket.gethostname()`in a regular python shell (returns just `'Ich'`) it returns the gaierror.

Thanks!
