### ISSUE TITLE
port is incorrectly read from ssh config file as a string, leading to AssertionError: PORT is not a number

### ISSUE THREAD

**Issue by n-loginov** [pahaz/sshtunnel#62]
When initializing SSHTunnelForwarder() with the default ssh config file, an AssertionError is raised:

Traceback (most recent call last):
  File "test_ssh.py", line 99, in <module>
    remote_bind_address=(mysql_host, int(mysql_port))) as server:
  File "/usr/local/lib/python2.7/dist-packages/sshtunnel.py", line 877, in __init__
    check_port(self.ssh_port)
  File "/usr/local/lib/python2.7/dist-packages/sshtunnel.py", line 76, in check_port
    assert isinstance(port, int), 'PORT is not a number'
AssertionError: PORT is not a number

Looking through the code, it seems that in _read_ssh_config(), ssh_port is taken "as is" from hostname_info. hostname_info, in turn, is the result of paramiko.SSHConfig().lookup() which returns port as string. Thus int assertion fails on ssh_port.

I was able to fix the issue by simply converting ssh_port to int in _read_ssh_config():
sshtunnel.py, line 911: ssh_port = ssh_port or hostname_info.get('port')
change to 
sshtunnel.py, line 911: ssh_port = ssh_port or int(hostname_info.get('port'))

Let me know if I'm missing something. Thanks.

**Comment by fernandezcuesta** [comment]
Hi, thanks for reporting! Indeed there is such problem as you mention. The solution is almost as simple as yours (just have to consider when `hostname_info.get('port')` returns `None`.

**Comment by n-loginov** [comment]
Thank you for the quick fix. I did miss that case...

I tried running my code with 0.0.8.3 and it did not work due to another error with the Proxy Command. I believe that's a minor bug as well; will file a separate ticket.
