### ISSUE TITLE
When connecting with a proxy command, AttributeError is raised from erroneously calling connect() on paramiko.proxy.ProxyCommand

### ISSUE THREAD

**Issue by n-loginov** [pahaz/sshtunnel#64]
In sshtunnel.py, in _get_transport(), the code erroneously calls connect() on _socket irregardless of the existence of self.ssh_proxy. This leads to an AttributeError when, for example, a config file has a proxy command. The reason for this is that in this case, _socket is not an instance of socket.socket but paramiko.proxy.ProxyCommand, which has no method connect() and should be passed directly into paramiko.Transport.

I think the change that needs to be made is moving lines 1022-1023 under the else clause, as it was the case with 0.0.8.2.

Traceback (most recent call last):
  File "test.py", line 116, in <module>
    remote_bind_address=(mysql_host, int(mysql_port))) as server:
  File "/usr/local/lib/python2.7/dist-packages/sshtunnel.py", line 1478, in __enter__
    self._raise(exception=exc_class, reason=exc, traceback=tb)
  File "/usr/local/lib/python2.7/dist-packages/sshtunnel.py", line 1007, in _raise
    raise exception(reason, traceback)
AttributeError: (AttributeError("'ProxyCommand' object has no attribute 'connect'",), <traceback object at 0x7f4c23b98998>)

    def _get_transport(self):
        """ Return the SSH transport to the remote gateway """
        if self.ssh_proxy:
            if isinstance(self.ssh_proxy, paramiko.proxy.ProxyCommand):
                proxy_repr = repr(self.ssh_proxy.cmd[1])
            else:
                proxy_repr = repr(self.ssh_proxy)
            self.logger.debug('Connecting via proxy: {0}'.format(proxy_repr))
            _socket = self.ssh_proxy
        else:
            _socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        **_socket.settimeout(SSH_TIMEOUT)**
        **_socket.connect((self.ssh_host, self.ssh_port))**
        transport = paramiko.Transport(_socket)
        transport.set_keepalive(self.set_keepalive)
        transport.use_compression(compress=self.compression)
        transport.daemon = self.daemon_transport

**Comment by fernandezcuesta** [comment]
Hi, thanks again for pointing this out.
Just applying those 2 lines when _socket is actually a socket object. Pushing changes in a second.

**Comment by n-loginov** [comment]
Thanks!
