### ISSUE TITLE
Use three digits for the version

### ISSUE THREAD

**Issue by pahaz** [pahaz/sshtunnel#65]
I think that this project is not so much to use four digits for versioning. It seems that the time has come to do release `0.1.0` and then up the last digit for new versions.

**Comment by fernandezcuesta** [comment]
@pahaz I need your help to add AppVeyor and readthedocs webhooks into this repo settings before attempting to release v0.1.0

**Comment by pahaz** [comment]
@fernandezcuesta I'm ready, I have to do?
