### ISSUE TITLE
Please release version 0.0.8.3 on pypi

### ISSUE THREAD

**Issue by mikeage** [pahaz/sshtunnel#67]
Hi,

I'd like to be able to use 0.0.8.3 (with the fix to gethostbyname_ex / gethostname for OS X, but I'd like to install from pypi, rather that pip install git+https. Can you please create a formal release? Thanks!

**Comment by fernandezcuesta** [comment]
Hi, yes that will be done as v0.1.0 as requested in #65

**Comment by mikeage** [comment]
Great, thanks! I'm currently using 0.0.3 (I know, right?) on several hundred tests a day on an internal CI system; we mirror the wheel so you don't see it in your statistics, but we're using it :)

**Comment by fernandezcuesta** [comment]
Released [version 0.1.0](https://pypi.python.org/pypi/sshtunnel/0.1.0)

**Comment by mikeage** [comment]
Thank you!
