### ISSUE TITLE
Ignore error

### ISSUE THREAD

**Issue by basnijholt** [pahaz/sshtunnel#76]
I am using this package in [my package](https://github.com/basnijholt/hpc05) to use `ipyparallel ` with our university cluster.

Sometimes if the connection is lost I am getting thousands of lines of the same [error](https://github.com/pahaz/sshtunnel/blob/master/sshtunnel.py#L380) printed, however for different ports. This sometimes crashes the notebook I am working in.

Is there an option to silent this error?

**Comment by basnijholt** [comment]
Thank you! Unfortunately, that doesn't work. Still getting a cascade of errors.

**Comment by fernandezcuesta** [comment]
@basnijholt I guess this might be because of ipython/jupyter creating a root logger, please try with the following:

    import logging
    logger = logging.getLogger()
    handler.setLevel(logging.CRITICAL)

Or even disable propagation with:

    logger.propagate = False

**Comment by basnijholt** [comment]
For some reason that also failed, but it pointed me in the right direction.

I now fixed it with: `import logging; logging.disable(logging.CRITICAL)`

Thanks for the help!
