### ISSUE TITLE
Why do threads (sshtunnel's srv-* and paramiko's transport) default to daemon = False

### ISSUE THREAD

**Issue by mikeage** [pahaz/sshtunnel#80]
I see that this changed in 0.0.4, and went back in 0.0.5, but what's the reason for _not_ using daemon=True threads? It means that if any tunnel isn't cleaned up, the main process will get stuck. Is there any harm is switching to daemon mode?

**Comment by fernandezcuesta** [comment]
Well I personally use daemon threads but if I remember correctly that was set back to False to be backwards compatible.

**Comment by mikeage** [comment]
ok, thanks. I've switched mine to daemon threads as well, but as this wasn't the default, I wanted to make sure I wasn't missing something important / risky.
