### ISSUE TITLE
Eventual crash

### ISSUE THREAD

**Issue by ek-nath** [pahaz/sshtunnel#94]
Hi,

I am trying to use the Forwarder as a context manager. For the longest period of time, it works just fine, but all of a sudden, it crashes with the following error:
I know the arguments are correct because this works consistently, just that when my script runs for a long time (multiple days), it crashes.

My question is how do I recover from this error? I am already trying this in an infinite loop with try catch.

<pre><code>while True:
    try:
        with SSHTunnelForwarder (...) as server:
            # Logic
            return result
    except:
        time.sleep(1)

<pre><code>2017-05-30 23:18:08,215| ERROR   | Could not establish connection from ('127.0.0.1', 42411) to remote side of the tunnel
2017-05-30 23:18:08,233| ERROR   | Secsh channel 3 open FAILED: Connection refused: Connect failed
2017-05-30 23:18:08,248| ERROR   | Could not establish connection from ('127.0.0.1', 42411) to remote side of the tunnel</code></pre>

**Comment by fernandezcuesta** [comment]
Is port 42411 part of your settings?
What is the error you are getting while catching the exception the first time?

**Comment by pahaz** [comment]
We really need your feedback. But if you still not responding we close the thread. 

We need to know your exception. Could you please provide us more information.

**Comment by ek-nath** [comment]
The problem is hard to reproduce and occurs once a month or so. I don't
have the exact error thrown.
42411 is what's generated at runtime by sshtunnel. If you'd like, this bug
can be closed till I observe it again.

**Comment by pahaz** [comment]
Do you have any news? Is it still happening? 
Could you please also provide us your Python version and your OS

**Comment by ek-nath** [comment]
I have stopped using this code in production for the time being, so there's
no way of reproducing this for me. This issue can be closed till it appears
again. The issue might be because of ssh itself and not because of this
library
