### ISSUE TITLE
SCP over tunnel (Question)

### ISSUE THREAD

**Issue by jwaligora** [pahaz/sshtunnel#95]
Hi. I'm trying to move a file via the open tunnel. Paramiko sftp seems to rely on the underlying ssh objects. I tried a few things (I'm not a Python expert, and networking is an outright enemy of mine). Playing with ._get_transport() and ._transport, against the TunnelForwarder object, got me as far as depositing my file on the forwarding server...not the destination one. I may be over-analyzing and missing the obvious. Please let me know what's the simplest way to code this. Thanks.

**Comment by fernandezcuesta** [comment]
Hi there,
Once the tunnel is established (I assume you're opening a tunnel to remote's port 22) you can create yet another paramiko [sftpclient](http://docs.paramiko.org/en/2.1/api/sftp.html) on the local listening port (i.e. `127.0.0.1:10022`).

**Comment by jwaligora** [comment]
Thanks! I got there last night with a bit of help from a friend. It just wasn't obvious to me that it would take 3 steps as opposed to just 2. All good now though.
