### ISSUE TITLE
Tuple index out of range when handling exception

### ISSUE THREAD

**Issue by dmulter** [pahaz/sshtunnel#96]
I've been using sshtunnel very successfully for quite some time now. I just happened to receive a rare failure creating the tunnel through my AWS NAT instance to my database. I know the code in my flask-script command for creating the tunnel is good. This exception exposed a problem in the sshtunnel code that tries to format an error message using the exception args.

The stack trace follows. Sorry that I can't reproduce the problem and have no more details.

```
Traceback (most recent call last):
22-Jun-2017 15:59:14      File "xxxxx/.virtualenv/local/lib/python2.7/site-packages/flask_script/__init__.py", line 412, in run
22-Jun-2017 15:59:14        result = self.handle(sys.argv[0], sys.argv[1:])
22-Jun-2017 15:59:14      File "xxxxx/.virtualenv/local/lib/python2.7/site-packages/flask_script/__init__.py", line 383, in handle
22-Jun-2017 15:59:14        res = handle(*args, **config)
22-Jun-2017 15:59:14      File "xxxxx/.virtualenv/local/lib/python2.7/site-packages/flask_script/commands.py", line 216, in __call__
22-Jun-2017 15:59:14        return self.run(*args, **kwargs)
22-Jun-2017 15:59:14      File "xxxxx/commands/upgrade_db.py", line 34, in run
22-Jun-2017 15:59:14        local_bind_address=(db_host, db_port_local)
22-Jun-2017 15:59:14      File "xxxxx/.virtualenv/local/lib/python2.7/site-packages/sshtunnel.py", line 1482, in __enter__
22-Jun-2017 15:59:14        self.start()
22-Jun-2017 15:59:14      File "xxxxx/.virtualenv/local/lib/python2.7/site-packages/sshtunnel.py", line 1221, in start
22-Jun-2017 15:59:14        self._create_tunnels()
22-Jun-2017 15:59:14      File "xxxxx/.virtualenv/local/lib/python2.7/site-packages/sshtunnel.py", line 1082, in _create_tunnels
22-Jun-2017 15:59:14        msg = 'Problem setting SSH Forwarder up: {0}'.format(e.args[0])
22-Jun-2017 15:59:14    IndexError: tuple index out of range
```

**Comment by fernandezcuesta** [comment]
Hi, thanks for raising this issue.
Loos like a bad assumption, exceptions MAY specify a variable. When this is
not the case it should be handled appropriately. Will fix it ASAP.

**Comment by fernandezcuesta** [comment]
Oh BTW looks to me like this was already solved in the past. Please ensure
you're using latest git release.

Regards

**Comment by pahaz** [comment]
@dmulter is your problem solved? Could your please provide us with feedback.

**Comment by dmulter** [comment]
I'm using the latest PyPI release, not sure if that's the latest here. Seems to have been a long time since a GitHub release. Anyway, the failure is so rare, I've only ever seen it once.

**Comment by fernandezcuesta** [comment]
@dmulter my mistake, I meant using the latest ~release~ **commit**. Anyway both pypi and gh release should be updated, @pahaz.
