### ISSUE TITLE
Tunnel hangs on database connect

### ISSUE THREAD

**Issue by thorstenkampe** [pahaz/sshtunnel#99]
I'm connecting to a variety of database (Oracle, PostgreSQL und MS SQL) via SQLAlchemy. Connecting to an Oracle database makes the tunnel hang. This does not happen for PostgreSQL or MS SQL or when using plink to create the tunnel.

I've created a trace log.

[oracle-hang.txt](https://github.com/pahaz/sshtunnel/files/1247149/oracle-hang.txt)

This is Python 3.6.2 64-bit on Windows. All modules have the latest version.
Regards, Thorsten

**Comment by fernandezcuesta** [comment]
@thorstenkampe could you please post a reproducible example?

**Comment by thorstenkampe** [comment]
```
import sqlalchemy, sshtunnel
```
Start tunnel
```
tunnel = sshtunnel.SSHTunnelForwarder(
                        ssh_address_or_host = 'HOST',
                        ssh_port            = 22,
                        ssh_username        = 'USER',
                        remote_bind_address = ('localhost', 1521),
                        local_bind_address  = ('localhost', 1521))
tunnel.start()
```
Use nping to verify it's running
```
SENT (3.1160s) Starting TCP Handshake > localhost:1521 (127.0.0.1:1521)
RCVD (3.1170s) Handshake with localhost:1521 (127.0.0.1:1521) completed
SENT (4.1200s) Starting TCP Handshake > localhost:1521 (127.0.0.1:1521)
RCVD (4.1210s) Handshake with localhost:1521 (127.0.0.1:1521) completed
```
Connect to database host directly to see that it's reachable
```
def connect():
    connstring = f'oracle://sys:PASSWORD@{HOST}/xe?mode=sysdba'
    engine     = sqlalchemy.create_engine(connstring, echo = True)
    conn       = engine.connect()

HOST = 'HOST'
connect()

2017-08-25 22:25:40,559 INFO sqlalchemy.engine.base.Engine SELECT USER FROM DUAL
2017-08-25 22:25:40,560 INFO sqlalchemy.engine.base.Engine {}
2017-08-25 22:25:40,562 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60 CHAR)) AS anon_1 FROM DUAL
2017-08-25 22:25:40,563 INFO sqlalchemy.engine.base.Engine {}
2017-08-25 22:25:40,564 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS NVARCHAR2(60)) AS anon_1 FROM DUAL
2017-08-25 22:25:40,565 INFO sqlalchemy.engine.base.Engine {}
```
Now use the tunnel - it hangs immediately
```
HOST = 'localhost'
connect()
```

```
SENT (200.8720s) Starting TCP Handshake > localhost:1521 (127.0.0.1:1521)
SENT (201.8730s) Starting TCP Handshake > localhost:1521 (127.0.0.1:1521)
SENT (202.8750s) Starting TCP Handshake > localhost:1521 (127.0.0.1:1521)
SENT (203.8760s) Starting TCP Handshake > localhost:1521 (127.0.0.1:1521)
```

**Comment by penfree** [comment]
i meet the same problem.
when use cxOracle to connect to database, everything is ok but it hangs when making a blob operation( read or get the size of blob field)

**Comment by matttan90** [comment]
Hi, I have the same issue that connection hangs whenever I try connecting to a mssql database. Specifically when I try to make a connection to the mssql database using pymssql.connect().

My use case is almost identical to Example 2, except it doesn't connect. Apologies, i'm quite new to python.

```
#singlemodule.py

tunnel = SSHTunnelForwarder(
    ssh_address_or_host='some-remoteserver-ip',
    ssh_port=22,
    ssh_username='someusername',
    ssh_private_key='/somewhere/key',
    ssh_private_key_password='somepassword',
    remote_bind_address = ('some-private-mssql-server-ip-accessiblebyremoteserver', 1555),
    local_bind_address = ('localhost', 5856),
) 

tunnel.start()

conn = pymssql.connect(server=tunnel.local_bind_host, 
                       user='mssql_username', 
                       password='mssql_password,
                       database='database_name', 
                       port=tunnel.local_bind_port)

# is at this part it hangs...
```

However, i find it weird that it works if i run both parts separately as two modules. Ie, run tunnel_module.py, and concurrently run connect_module.py in-parallel with 2 python interpreters.

```
#tunnel_module.py

tunnel = SSHTunnelForwarder(
    ssh_address_or_host='some-remoteserver-ip',
    ssh_port=22,
    ssh_username='someusername',
    ssh_private_key='/somewhere/key',
    ssh_private_key_password='somepassword',
    remote_bind_address = ('some-private-mssql-server-ip-accessiblebyremoteserver', 1555),
    local_bind_address = ('localhost', 5856),
) 

tunnel.start()

#connect_module.py

conn = pymssql.connect(server=tunnel.local_bind_host, 
                       user='mssql_username', 
                       password='mssql_password,
                       database='database_name', 
                       port=tunnel.local_bind_port)

# *do other stuff, and it works.
```

**Comment by fernandezcuesta** [comment]
Hi,
as a general recommendation please run your code inside a `with` statement. Something like:

    with SSHTunnelForwarder(
        ssh_address_or_host='some-remoteserver-ip',
        ssh_port=22,
        ssh_username='someusername',
        ssh_private_key='/somewhere/key',
        ssh_private_key_password='somepassword',
        remote_bind_address = ('some-private-mssql-server-ip-accessiblebyremoteserver', 1555),
        local_bind_address = ('localhost', 5856),
    ) as tunnel:  # This will start/stop the tunnel
        with pymssql.connect(
            server=tunnel.local_bind_host, 
            user='mssql_username', 
            password='mssql_password,
            database='database_name', 
            port=tunnel.local_bind_port
        ) as cursor:  # This will start/stop the DB connection
            sql = "SELECT `id`, `password` FROM `users` WHERE `email`=%s"
            cursor.execute(sql, ('webmaster@python.org',))
            result = cursor.fetchone()
            print(result)

**Comment by matttan90** [comment]
Hi fernandez,

Thanks for your quick reply! I've tried with the nested `with` statements and it still hangs... We've tried debugging  and ran a subprocess to see if the tunnel works, and it does. 

```
with SSHTunnelForwarder(
    ssh_address_or_host='some-remoteserver-ip',
    ssh_port=22,
    ssh_username='someusername',
    ssh_private_key='/somewhere/key',
    ssh_private_key_password='somepassword',
    remote_bind_address = ('some-private-mssql-server-ip-accessiblebyremoteserver', 1555),
    local_bind_address = ('localhost', 5856),
) as tunnel:  # This will start/stop the tunnel

<< AT THIS SECTION OF DEBUGGING >>
Ran subprocess.check_output on "nc -z localhost 5856" and results :
Connection to localhost port 5856 [tcp/opsession-prxy] succeeded!

    with pymssql.connect(
        server=tunnel.local_bind_host, 
        user='mssql_username', 
        password='mssql_password,
        database='database_name', 
        port=tunnel.local_bind_port
    ) as cursor:  # This will start/stop the DB connection
        sql = "SELECT `id`, `password` FROM `users` WHERE `email`=%s"
        cursor.execute(sql, ('webmaster@python.org',))
        result = cursor.fetchone()
        print(result)
```

However pymssql connection doesn't seem to work.. Just wondering if theres any interaction with pymssql and the tunnel in any unintended way?

**Comment by fernandezcuesta** [comment]
Not sure how, need to reproduce it with a MS SQL database and pymssql.
No issues found with MariaDB and PyMySQL.

**Comment by thorstenkampe** [comment]
Can't reproduce the issue anymore - thus closing the ticket. Thanks for the fantastic, simple and stable module.

**Comment by dgoo2308** [comment]
working with SSHtunnel4.0 and still the same issue, yes not adding database in the connect helps.

**Comment by d0rc** [comment]
Same code works on mac and fails on Linux. Reproducing on each launch. Code is very basic, it feels like it has something to do we simultaneous connections.

**Comment by hattaagung** [comment]
same issue with SSHtunnel4.0. 
In windows, it is working but in linux not working.
